baseURL = "https://hcartiaux.github.io/"
languageCode = "en-us"
title = "My sysadmin notes"
theme = "solar-theme-hugo"
paginate = 5
pygmentsStyle = "solarized-dark" # solarized-light, -dark or -dark256
copyright = "CC BY-SA 4.0"

[params]
  scheme = "dark"
  description = "Btw I use arch"

#[menu]
#  [[menu.main]]
#    name = "Home"
#    url = "/index.html"
#  [[menu.myself]]
#    name = "My github"
#    url = "https://github.com/hcartiaux/"
